### PR TITLE
setWritable, valueType correction

### PR DESCRIPTION
**Pull request by egekorkan**
value type correction is done once again
I have added a function to set the writable field to true or false, this is then used in createFromDescription
Also createFromDescription was assuming that the "Property" is the first element of the type array, now it checks if it exists in the array

### CODE REVIEW

**Comment by danielpeintner** [comment]
Hi @egekorkan . Thanks for your work again. There are still conflicts. Can you try to resolve them?

**Comment by egekorkan** [comment]
I am not that accustomed with git but there is a very annoying problem in client-example.ts. The imports are not correct and if I change them I get a conflict. I have no idea why :)

**Comment by danielpeintner** [comment]
It look issues are gone and we can merge this PR.

Once merged I ill need to merge with the outstanding PR wr.t. to the new API (see https://github.com/thingweb/node-wot/pull/67)

**Comment by danielpeintner** [comment]
I merge it for now and will try to align it with the new API (which does not provide anymore createFromDescription)

**Pull request merged**
